[build]
  base = "quoridor-client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://quoridoronline-5ngr.onrender.com"
  REACT_APP_WS_URL = "wss://quoridoronline-5ngr.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
